name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install trunk & wasm-bindgen
        run: |
          cargo install trunk
          cargo install wasm-bindgen-cli

      - name: Build (Trunk)
        run: trunk build --release
